
import type { Metadata } from "next";
import "./global_styles/reset/reset.scss";
import Panel from "./utils/panel/panel";
import LoaderComponent from "./share/loader/loader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main>
          <Panel />
          <LoaderComponent />
          {children}
        </main>
      </body>
    </html>
  );
}
